version: '2'


services:
  php:
    build: php
    ports:
      - 9000:9000

  nginx:
    build: nginx
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
