version: '2'


services:
  php:
    image: registry.cn-shanghai.aliyuncs.com/bigpang/dnmp_php
    volumes:
      - ./www:/var/www/html:rw
      - ./config/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./config/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
    restart: always
    environment:
      TZ: "$TZ"
    ports:
      - 9000:9000

  nginx:
    image: nginx
    volumes:
      - ./www:/var/www/html:rw
      - ./logs/nginx:/var/log/nginx
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    environment:
      TZ: "$TZ"
    ports:
      - 80:80
      - 443:443

  node:
    image: node:12.7.0-alpine
    working_dir: /var/www/html
    volumes:
      - ./www:/var/www/html:rw
    environment:
      TZ: "$TZ"
    command: "yarn config set registry http://registry.npm.taobao.org/"

  es:
    image: elasticsearch:6.5.3
    ports:
      - 9200:9200
      - 9300:9300
